### ISSUE TITLE
Add `AllSettled` method to package.

### ISSUE THREAD

**Issue by elycruz** [chebyrash/promise#10]
Spec Reference:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled

Example reference:
https://github.com/tc39/proposal-promise-allSettled#examples

Example reference: 
https://github.com/tc39/proposal-promise-allSettled#real-world-scenarios

### Method
- [ ] - AllSettled

### Tests
- [ ] - With `nil` promises.
- [ ] - With an empty list of promises (same as above just explicit).
- [ ] - With only one passing promise.
- [ ] - With only passing promises.
- [ ] - With only one failing promise.
- [ ] - With only failing promises.
- [ ] - With a mix of passing and failing promises.

**Comment by chebyrash** [comment]
Thanks for creating this issue. I read the code from the Race PR where you started working on the AllSettled method. Could you explain the reasoning behind the Result type and why it's needed? Reading the spec I see the following ```Returns ... an array of objects that each describe the outcome of each promise.``` meaning that ```AllSettled[Promise("hello"), Promise("world"), Promise(willError)]``` will return ```["hello", "world", someError]``` and the user can do a for loop and switch on the each element's type

**Comment by elycruz** [comment]
Sure, not a problem :+1: .
If you run the example on the mdn site with the following change:
`console.log(result.status)` to `console.log(result)` you'll see that `result` is actually
an object.  Link: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled

**Comment by elycruz** [comment]
Woops, also seems only chrome 76 and up currently supports `Promise.allSettled`,

**Comment by elycruz** [comment]
Though also, if you see the line (in the example (mdn example)) you'll see they're actually referencing the contained promise status via `result.status` (hence what I did :))).

**Comment by elycruz** [comment]
Ah, here is a good description (from the 'allSettled' draft):
https://tc39.es/proposal-promise-allSettled/

**Comment by chebyrash** [comment]
Yes, you are quite right
I think we should research how this method is implemented in another languages since it's only a draft / proposal in JS

**Comment by chebyrash** [comment]
This does actually look pretty good:
https://github.com/tc39/proposal-promise-allSettled#examples
https://github.com/tc39/proposal-promise-allSettled#real-world-scenarios

**Comment by chebyrash** [comment]
I think we should do it your way, the way JS drafted it with the results objects (status, value, reason), so it's consistent and follows the design

**Comment by elycruz** [comment]
Right, I agree.
I'll start up a new branch for it shortly 👍 ,

**Comment by chebyrash** [comment]
I've decided to avoid the result object way until we get proper generics in Go 2.0 because the result type is lost due to interface{} return value of the promise.

Right [now](https://github.com/chebyrash/promise#allsettled) the user should type switch on the returned value (error or some known-to-user type)

**Comment by elycruz** [comment]
Aha, I didn't think about that before haha, yes I agree.  Result is lost and is hard to know what is returned unless written in docs (I.e., the only way to know is via docs).  Good work 👍 .

**Comment by chebyrash** [comment]
Thanks a lot for pointing out the  way JS implements this.
I definitely want to come back to that when we get generics and the type will no longer be lost.
