### ISSUE TITLE
Promise.all slice

### ISSUE THREAD

**Issue by jakesyl** [chebyrash/promise#15]
Hi,

Is there a way to perform `promise.All()` on a slice? Something like this:

```
		for _, completedTransaction := range promises {
			completedTransaction.Await()
		}
```

but built in. I realize a workaround is available now by using reflection, but this doesn't work with too many values.

**Comment by chebyrash** [comment]
Sure you can.

Reusing the example from readme
```go
var arr = []*promise.Promise {
		promise.Resolve(321),
		promise.Resolve("Hello, World"),
		promise.Resolve([]string{"one", "two", "three"}),
	}

results, _ := promise.All(arr...).Await()
fmt.Println(results)
```

Notice how the **...** after the **arr**
It unpacks all elements of the array/slice into arguments for this function.
You can read about it here - https://gobyexample.com/variadic-functions

Code for your snippet:
```go
var result = promise.All(promises...).Await()
```

**Comment by jakesyl** [comment]
Perfect! Thanks
