### ISSUE TITLE
Any plans to add remainder of JS promise interface to this implementation?

### ISSUE THREAD

**Issue by elycruz** [chebyrash/promise#2]
The specification for javascript promises has evolved by a couple of methods since this library was created and was just wondering if we should start hacking up the remaining JS promise methods into the lib?

MDN reference:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

Also I started hacking them up here: https://github.com/elycruz/promise/tree/issue-%23-js_promise_interface (for my own benefit :-D).

Thanks 👍

**Comment by elycruz** [comment]
K, great, will take the issue then 👍 
(thanks 👍)

**Comment by chebyrash** [comment]
Thanks for the work you've already done.
I think we should add the following methods:
1) All
2) AllSettled
3) Race

You have already implemented 1 and 3 👍
Let's try 2 as well

**Comment by elycruz** [comment]
Sure, it's not a problem, it's my pleasure :+1: 
Agreed!  Will clean up the implementations of `All` and `Race` and then give `AllSettled` some thought jehjeh :+1:.

**Comment by chebyrash** [comment]
This is mainly done and merged into master!
There are a couple of other methods we can think about implementing (borrowed from other languages), but other than that it's the ES6 implementation is done

**Comment by elycruz** [comment]
Agreed.
