### ISSUE TITLE
Range over promise.All

### ISSUE THREAD

**Issue by metehus** [chebyrash/promise#22]
So, i'm working on something like this:

```go
artists, err := promise.All(promises...).Await()

for _, artist := range artists {
    doSomethingWith(artist)
}

```

But, because `.Await()` returns a `interface{}`, i can't range through it 
![image](https://user-images.githubusercontent.com/22124518/93217243-27be3a80-f73f-11ea-84fc-36110a6687c0.png)

I also tried to specify the type:
```go
var artists []*structs.ArtistResponse
artists, _ = promise.All(promises...).Await()

for _, artist := range artists {
    doSomethingWith(artist)
}

```

But then, i receive this:
![image](https://user-images.githubusercontent.com/22124518/93217350-54725200-f73f-11ea-89d2-3d9df130a3ea.png)

I'm using Go 1.15

**Comment by chebyrash** [comment]
Hi @metehus 

Right now the best you can do is something like this:
```go
type Artist struct {
	Name string
}

func getArtist(name string) *promise.Promise {
	return promise.Resolve(Artist{Name: name})
}

func doSomethingWith(artist Artist) {
	fmt.Println(artist.Name)
}

func main() {
	artists, _ := promise.All(
		getArtist("aaa"),
		getArtist("bbb"),
		getArtist("ccc"),
	).Await()

	for _, a := range artists.([]interface{}) {
		doSomethingWith(a.(Artist))
	}
}
```

This is because `.Await()` returns `interface{}` type since Go doesn't support generics ([yet](https://blog.golang.org/generics-next-step))

**Comment by metehus** [comment]
Oh cool, that worked, i also casted it into the range already
```go
	for _, artist := range artists.([]*structs.ArtistResponse) {
		doSomethingWith(artist)
	}
```
Thank you so much!
