### ISSUE TITLE
Questions: run in parallel and stop

### ISSUE THREAD

**Issue by DavidMet** [chebyrash/promise#23]
HI,

Few questions.

1. Does each `promise` run in go routine ? 
2. in case each promise run in go-routine , is it possible to use timeout ?

 e.g. in case you are running `promise.all` for promise A and promise B and you want to wait for 10 seconds for all the responses (time limit) ,but promise `A` continue to run (possible forever due to some issue), is it possible to **kill** promise `A` after the 10 seconds ? (when you want to get the results with the time limt) 

Thanks!

**Comment by chebyrash** [comment]
Hello

1. Yes.

2. Yes, you can implement your function to use `context` or use the `time` package (see [example](https://gobyexample.com/timeouts))
When you mentioned killing promises I'm assuming forceful termination, and in that regard the answer is no. Go runtime does not provide a way to kill a specific goroutine.
See this answer: https://github.com/golang/go/issues/32610#issuecomment-501958267
