### ISSUE TITLE
promise.Any does not exist

### ISSUE THREAD

**Issue by JulienLecoq** [chebyrash/promise#25]
In the README as well as in the examples, you use ```promise.Any``` for typing but it is not exported by the package.

**Comment by chebyrash** [comment]
That's true.

I'm in the middle of updating the README to showcase the new update which utilises Go 1.18 generics.

Actually, the old `promise.Any` won't be needed any more with the introduction of native `any` in Go

**Comment by JulienLecoq** [comment]
Okay, can't wait to see it in action :D

**Comment by chebyrash** [comment]
done
