### ISSUE TITLE
Add `All` method to 'promise' package

### ISSUE THREAD

**Issue by elycruz** [chebyrash/promise#3]
Creating separate issue for each method we're working on adding into the lib (this one's just for the `All` method).

### Methods:
- [x] - `All`

### Tests:
- [x] - `All`
  - [x] - With no promises.
  - [x] - With resolved promises (1 or more).
  - [x] - With only resolved promises (1 or more).
  - [x] - With failing promises (1 or more).
  - [x] - With only failing promises (1 or more).

**Comment by chebyrash** [comment]
Good work!

**Comment by elycruz** [comment]
Great :-D,  :-) 👍
