### ISSUE TITLE
Can it support to combined with a goroutine pool as the resource of the future using, like the Future In Java?

### ISSUE THREAD

**Issue by PursuingPing** [chebyrash/promise#31]
Future I think it can make the code more clear without doubt, and sometimes it using the flight goroutine to running its 'Job'， which is little not suitable for the web server. So can the future using the goroutine pool resource to running ? Thanks.

**Comment by chebyrash** [comment]
It's possible to run the executor goroutine using a pool. Any of [these](https://github.com/avelino/awesome-go#goroutines) should do the job.

**Comment by chebyrash** [comment]
@PursuingPing there's now pool support available in master 🙂
