### ISSUE TITLE
Then and Catch as methods of Promise

### ISSUE THREAD

**Issue by goodevilgenius** [chebyrash/promise#32]
In the JavaScript Promise API, then and catch are methods on the Promise prototype. It would be useful if that were implemented here to follow that convention and allow a more fluent API.

Doing this would be handy:

```go
func GetPromise(): *promise.Promise[int] {
  // code here
}

func main() {
  ctx := context.Background()
  GetPromise().Then(ctx, func(i int) (int, error) {
    fmt.Println(i)
    return i, nil
  }).Catch(ctx, func(err error) error {
    fmt.Println(err)
    return err
  })
}
```

**Comment by chebyrash** [comment]
I wish this was possible!

The function would look something like this:
```go
func (p *Promise[A]) Then[B any](ctx context.Context, resolve func(A) (B, error)) *Promise[B]
```

However Go doesn't allow you to specify type parameters on methods of generic types 😢 
![image](https://github.com/user-attachments/assets/62165dee-87b5-46db-81bb-65ea5e89fadb)

**Comment by goodevilgenius** [comment]
> However Go doesn't allow you to specify type parameters on methods of generic types 😢

Oh, that's interesting, and very disappointing. What an odd restriction.
