### ISSUE TITLE
Add `Race` method to the package

### ISSUE THREAD

**Issue by elycruz** [chebyrash/promise#5]
This is the only other method from the JS Ecmascript 2015 standard that is not implemented here (other than the `All` method (which has a pull request on the way)).

Link to 'race' docs on MDN:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race

This issue will be to track the work done on it:

Method:
- [x] - `Race`

Tests:
- [x] - With no promises.
- [x] - With one promise, a passing one.
- [x] - With multiple passing promises.
- [x] - With one promise, a failing one.
- [x] - With multiple promises and one failing.
- [x] - With multiple failing promises.

**Comment by chebyrash** [comment]
Thanks a lot for your work and the tests!

**Comment by elycruz** [comment]
Sure not a problem :+1:
