### ISSUE TITLE
Refactor tests

### ISSUE THREAD

**Issue by chebyrash** [chebyrash/promise#9]
A lot of older tests need to be refactored to follow the new style proposed by @elycruz

**Comment by chebyrash** [comment]
I believe there is a of bit work to do here (no one likes to write tests 😞)

**Comment by elycruz** [comment]
Hahaha, I agree (that is the case sometimes haha).  I've written all the test cases for all the ES6 methods in table format at the repo listed below (all we have to do is change the tests up where ever the interfaces don't match to get them working with this repo):  https://github.com/elycruz/ecms-go-promise/blob/master/Promise_test.go

**Comment by chebyrash** [comment]
Good stuff! I have a look at this

**Comment by elycruz** [comment]
Thanks! K 👍
